### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by fiskryeziu** [alokVerma749/foody-monk#34]
I'm getting cors error when visiting the deployed of this app

**Comment by alokVerma749** [comment]
yes,it is because we are using a third party API,
You can just use a browser extension `cors unblock` to bypass this error.

**Comment by alokVerma749** [comment]
we are working on this error it will be fixed soon.
Till then please use this browser extension

**Comment by alokVerma749** [comment]
We are happy to inform you that with the commit: e56be1279dbd5594692fb427d4e9b681162b563b , this issue has been resolved.
you can now interact with our web app without getting any `CORS` error.
Happy to have you onboard ❤️
