### ISSUE TITLE
Add alt text in menu item image

### ISSUE THREAD

**Issue by alokVerma749** [alokVerma749/foody-monk#39]
In cart provide a `alt` text to the image, by default it has alt text as `polaroid camera` change it to **image not provided**
![image](https://github.com/alokVerma749/foody-monk/assets/87599400/f5ab41dd-db2d-4dc4-9855-fceff66674f1)

**Comment by Abhishekm0410** [comment]
I would like to work on this as my first issue.

**Comment by Abhishekm0410** [comment]
Hello @alokVerma749 I have downloaded the said dependencies on my system but I am facing an issue while using npm run dev command. Can you help mw with this I am pasting the error for you.
$ npm run dev
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Dell\AppData\Roaming\SPB_Data/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Dell\AppData\oaming\SPB_Data\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Local\npm-cache\_logs\2023-07-15T11_54_36_99Z-debug-0.log

**Comment by alokVerma749** [comment]
Hey there, make sure to follow contribution guideline where you can find steps to  contribute to the project https://github.com/alokVerma749/foody-monk/blob/master/CONTRIBUTING.md

**Comment by alokVerma749** [comment]
## Regarding above

> Hello @alokVerma749 I have downloaded the said dependencies on my system but I am facing an issue while using npm run dev command. Can you help mw with this I am pasting the error for you. $ npm run dev npm ERR! code ENOENT npm ERR! syscall open npm ERR! path C:\Users\Dell\AppData\Roaming\SPB_Data/package.json npm ERR! errno -4058 npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Dell\AppData\oaming\SPB_Data\package.json' npm ERR! enoent This is related to npm not being able to find a file. npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Dell\AppData\Local\npm-cache_logs\2023-07-15T11_54_36_99Z-debug-0.log

## It looks like you haven't opened your terminal in the cloned repository, here are some steps you can follow:

* open your terminal and clone the repo.
```bash
git clone https://github.com/alokVerma749/foody-monk.git
```
* Then open your terminal in the foody-monk folder.
```bash
cd foody-monk
```
* Then run the command to download all the dependencies.
``` bash

 npm ci

``` 
* After the download, run the below command to start a server on your local host.
```bash
npm run dev
```

**Comment by alokVerma749** [comment]
commit: e36a813d3b7c05fcaa767152e5626366f13007c1 resolves this issue
