### ISSUE TITLE
changes in admin panel

### ISSUE THREAD

**Issue by alokVerma749** [alokVerma749/foody-monk#40]
## In the orders list of the admin page, there is not any information about which item belongs to which restaurant, add a restaurant name field also.
![image](https://github.com/alokVerma749/foody-monk/assets/87599400/08347364-fc31-4e42-83e4-4f9718220a5d)

# **NOTE**: 
* Check if restaurant data is coming as a response or not, if not then discuss it with us we will configure the backend to send the appropriate data

**Comment by riddhesh-flamecloud** [comment]
@alokVerma749 Hey I am trying to open this page but getting error 401 for "https://foody-monk-2.onrender.com/admin/orders". I am getting the alert in UI with error "You are not an admin".

Can you please share some test admin credentials. So I can check the issue. Also I want to work on this issue, can you please assign it to me.

**Comment by riddhesh-mahajan** [comment]
@alokVerma749  Hey I am trying to open this page but getting error 401 for "https://foody-monk-2.onrender.com/admin/orders". I am getting the alert in UI with error "You are not an admin". 

Can you please share some test admin credentials. So I can check the issue. 

I want to work on this issue, can you please assign it to me.

**Comment by alokVerma749** [comment]
sure @riddhesh-mahajan , 
you can use 
EMAIL: demoadmin123@gmail.com
PASSWORD: admin123
to login

**Comment by riddhesh-mahajan** [comment]
Hey @alokVerma749,

I was able to login using provided credentials but still getting the same error if I try to open "/admin".

Error
URL: https://foody-monk-2.onrender.com/admin/orders
Error Code: 501
Response: {"success":false,"message":"This is an admin route"}

Maybe this user don't have the admin role. @alokVerma749 Can you please check from the backend. Let me know once you updated the role for this user.

**Comment by alokVerma749** [comment]
ok now you will be able to log in 👍, sorry for the inconvenience

**Comment by riddhesh-mahajan** [comment]
I got the access, thanks.

**Comment by riddhesh-mahajan** [comment]
@alokVerma749 we are not getting any data related to Restaurant. 

I also noticed, there is a key "hideRestaurantDetails", currently it is "true".

Can you please update the backend to send the restaurant data for each card in "
https://foody-monk-2.onrender.com/admin/orders"

**Comment by alokVerma749** [comment]
We are currently reviewing the backend configuration and will make the necessary updates. we will notify you as soon as the necessary changes have been implemented

**Comment by alokVerma749** [comment]
He there, the issue has been resolved successfully. The data configuration has been updated, and now the restaurant name is visible using the `cartItem.name` in the `Admin.js page`.
If you have any further questions, please let us know.
